export const PRODCUT_LIST_REQUEST = "PRODCUT_LIST_REQUEST";
export const PRODCUT_LIST_SUCCESS = "PRODCUT_LIST_SUCCESS";
export const PRODCUT_LIST_FAIL = "PRODCUT_LIST_FAIL";

export const PRODCUT_DETAILS_REQUEST = "PRODCUT_DETAILS_REQUEST";
export const PRODCUT_DETAILS_SUCCESS = "PRODCUT_DETAILS_SUCCESS";
export const PRODCUT_DETAILS_FAIL = "PRODCUT_DETAILS_FAIL";

export const PRODUCT_CATEGORY_LIST_REQUEST = "PRODUCT_CATEGORY_LIST_REQUEST";
export const PRODUCT_CATEGORY_LIST_SUCCESS = "PRODUCT_CATEGORY_LIST_SUCCESS";
export const PRODUCT_CATEGORY_LIST_FAIL = "PRODUCT_CATEGORY_LIST_FAIL";
// create user constant

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";
